name: CI - Docker

on:
  push:
    branches:
      - feature/allow-run-as-container

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: e1himself/goss-installation-action@v1
        with:
          version: 'v0.4.4'

      - name: Build image
        run: docker build -t drevops/shellvar:test-shellvar .

      - name: Show images information
        run: docker images

      - name: Test image
        run: dgoss run drevops/shellvar:test-shellvar tail -f /dev/null
